<?php

$inscricoes_queries = array();

$inscricoes_queries[] = 'DROP TABLE IF EXISTS `teia_inscricoes`;';
$inscricoes_queries[] = 'CREATE TABLE teia_inscricao (
  `id` int(11) NOT NULL AUTO_INCREMENT,
 nome VARCHAR(255),
 email VARCHAR(255),
 cpf VARCHAR(255) collate utf8_unicode_ci, 
 estado VARCHAR(255) collate utf8_unicode_ci, 
 municipio VARCHAR(255) collate utf8_unicode_ci, 
 logradouro VARCHAR(255) collate utf8_unicode_ci, 
 complemento VARCHAR(255) collate utf8_unicode_ci, 
 bairro VARCHAR(255) collate utf8_unicode_ci, 
 localizacao VARCHAR(255) collate utf8_unicode_ci, 
 ocupacao VARCHAR(255) collate utf8_unicode_ci, 
 atuacao VARCHAR(255) collate utf8_unicode_ci, 
 telefone_cel VARCHAR(255) collate utf8_unicode_ci, 
 telefone_res VARCHAR(255) collate utf8_unicode_ci, 
 telefone_com VARCHAR(255) collate utf8_unicode_ci, 
 website VARCHAR(255) collate utf8_unicode_ci, 
 facebook VARCHAR(255) collate utf8_unicode_ci, 
 twitter VARCHAR(255) collate utf8_unicode_ci, 
 youtube VARCHAR(255) collate utf8_unicode_ci, 
 google_plus VARCHAR(255) collate utf8_unicode_ci, 
 outras_redessociais VARCHAR(255) collate utf8_unicode_ci, 
 curriculo LONGTEXT,
 data_nascimento VARCHAR(255) collate utf8_unicode_ci, 
 estado_civil VARCHAR(255) collate utf8_unicode_ci, 
 sexo VARCHAR(255) collate utf8_unicode_ci, 
 rg VARCHAR(255) collate utf8_unicode_ci, 
 orgao_emissor VARCHAR(255) collate utf8_unicode_ci, 
 data_chegada VARCHAR(255) collate utf8_unicode_ci, 
 data_saida VARCHAR(255) collate utf8_unicode_ci, 
 telefone_emergencia VARCHAR(255) collate utf8_unicode_ci, 
 representa_ponto_de_cultura VARCHAR(255) collate utf8_unicode_ci, 
 representa_gestor VARCHAR(255) collate utf8_unicode_ci, 
 representa_outro VARCHAR(255) collate utf8_unicode_ci, 
 entidade_nome VARCHAR(255) collate utf8_unicode_ci, 
 entidade_funcao VARCHAR(255) collate utf8_unicode_ci, 
 entidade_telefone VARCHAR(255) collate utf8_unicode_ci, 
 entidade_email VARCHAR(255) collate utf8_unicode_ci, 
 entidade_homepage VARCHAR(255) collate utf8_unicode_ci, 
 observacoes_clinicas VARCHAR(255) collate utf8_unicode_ci, 
 observacoes_clinicas_detalhes TEXT collate utf8_unicode_ci, 
 alergia VARCHAR(255) collate utf8_unicode_ci, 
 alergia_detalhes VARCHAR(255) collate utf8_unicode_ci, 
 tipo_sanguineo VARCHAR(255) collate utf8_unicode_ci, 
 fator_rh VARCHAR(255) collate utf8_unicode_ci, 
 plano_saude VARCHAR(255) collate utf8_unicode_ci, 
 plano_saude_detalhes VARCHAR(255) collate utf8_unicode_ci, 
 deficiencia VARCHAR(255) collate utf8_unicode_ci, 
 deficiencia_detalhes VARCHAR(255) collate utf8_unicode_ci, 
 deficiencia_acompanhante VARCHAR(255) collate utf8_unicode_ci, 
 deficiencia_acompanhante_parentesco TEXT collate utf8_unicode_ci, 
 deficiencia_observacoes TEXT collate utf8_unicode_ci, 
 alimentacao VARCHAR(255) collate utf8_unicode_ci, 
 alimentacao_especifica VARCHAR(255) collate utf8_unicode_ci, 
 alimentacao_alergia VARCHAR(255) collate utf8_unicode_ci, 
 alimentacao_alergia_detalhes VARCHAR(255) collate utf8_unicode_ci, 
 outras_observacoes TEXT collate utf8_unicode_ci, 
 presenca VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_ponto_cultura VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_gestor VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_indigena VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_matriz_africana VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_cigano VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_pesquisador VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_brasil_plural VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_representante_comites VARCHAR(255) collate utf8_unicode_ci, 
 segmentos_outros VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_forum_nacional_pontos_cultura VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_forum_indigena VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_forum_culturas_negras VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_forum_gestores_culturaviva VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_encontro_pontos_memoria VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_encontro_pontos_leitura VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_encontro_pesquisadores_politicas_culturais VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_seminario_acessibilidade VARCHAR(255) collate utf8_unicode_ci, 
 dialogos_conferencia_livre_educacao_cultura VARCHAR(255) collate utf8_unicode_ci,
  PRIMARY KEY  (`id`),
UNIQUE KEY cpf (`cpf`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;';